// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

// Package schema provides the on disk format for
// github.com/nthnca/object-store

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectSet struct {
	Item                 []*Object `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ObjectSet) Reset()         { *m = ObjectSet{} }
func (m *ObjectSet) String() string { return proto.CompactTextString(m) }
func (*ObjectSet) ProtoMessage()    {}
func (*ObjectSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *ObjectSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectSet.Unmarshal(m, b)
}
func (m *ObjectSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectSet.Marshal(b, m, deterministic)
}
func (m *ObjectSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectSet.Merge(m, src)
}
func (m *ObjectSet) XXX_Size() int {
	return xxx_messageInfo_ObjectSet.Size(m)
}
func (m *ObjectSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectSet.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectSet proto.InternalMessageInfo

func (m *ObjectSet) GetItem() []*Object {
	if m != nil {
		return m.Item
	}
	return nil
}

type Object struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimestampNanoSeconds int64    `protobuf:"varint,2,opt,name=timestamp_nano_seconds,json=timestampNanoSeconds,proto3" json:"timestamp_nano_seconds,omitempty"`
	Object               []byte   `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Object) GetTimestampNanoSeconds() int64 {
	if m != nil {
		return m.TimestampNanoSeconds
	}
	return 0
}

func (m *Object) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectSet)(nil), "schema.ObjectSet")
	proto.RegisterType((*Object)(nil), "schema.Object")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x89, 0x91, 0x40, 0xc7, 0x22, 0x12, 0xa4, 0x64, 0x19, 0xba, 0xca, 0xaa, 0x82, 0x7a,
	0x0e, 0x85, 0xf4, 0x00, 0x25, 0xad, 0x03, 0xad, 0x92, 0xa4, 0x98, 0xd9, 0x78, 0x7b, 0xb1, 0x29,
	0xee, 0xe6, 0xf1, 0xe6, 0x7f, 0x3e, 0x94, 0x69, 0x18, 0xd1, 0xbb, 0x66, 0x7e, 0x47, 0x8a, 0x52,
	0x64, 0xaa, 0x4f, 0x50, 0xdc, 0xfb, 0x27, 0x0e, 0xd4, 0x22, 0xc9, 0x1a, 0xb6, 0x13, 0xa1, 0x57,
	0x4c, 0x73, 0xb3, 0x3b, 0xef, 0x9b, 0x35, 0x91, 0x1f, 0xec, 0xe2, 0xea, 0x11, 0x44, 0x66, 0x79,
	0x00, 0xfe, 0xc2, 0x8f, 0x62, 0x9a, 0x99, 0xc2, 0xfe, 0x4e, 0x79, 0x85, 0x8a, 0x26, 0x8f, 0x89,
	0x9c, 0x9f, 0xbb, 0xe0, 0x42, 0xec, 0x12, 0x0e, 0x31, 0x3c, 0x92, 0xda, 0x68, 0x66, 0xb8, 0x3d,
	0xfe, 0xed, 0xcd, 0x85, 0xd8, 0x66, 0x27, 0x2b, 0x10, 0x71, 0x69, 0x54, 0x5c, 0x33, 0x53, 0xda,
	0x95, 0x7a, 0xb1, 0x2c, 0xbd, 0x7c, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x50, 0x11, 0xd0, 0xb9,
	0x00, 0x00, 0x00,
}
